"""Build-time submodule revisions. Auto-generated by setup.py."""
PICOQUIC_SHA      = '6a14757829ea31fe08d29b61e1947331da54fb1c'
PICOQUIC_DESCRIBE = '6a147578'
PICOQUIC_DATE     = '2026-05-30 22:45:42 -0700'
PICOQUIC_SUBJECT  = 'Merge pull request #2110 from private-octopus/fix-wt_baton_capsule_leak'
PICOTLS_SHA       = 'f350eab60742138ac62b42ee444adf04c7898b0d'
PICOTLS_DESCRIBE  = 'f350eab'
PICOTLS_DATE      = '2025-07-16 15:55:42 +0900'
PICOTLS_SUBJECT   = 'Merge pull request #574 from h2o/kazuho/pr570'
