"""Build-time submodule revisions. Auto-generated by setup.py."""
PICOQUIC_SHA      = 'eee50c1d36def7de19e0130fa2a4a1980a4123c6'
PICOQUIC_DESCRIBE = 'eee50c1d'
PICOQUIC_DATE     = '2026-06-02 12:07:33 -0700'
PICOQUIC_SUBJECT  = 'Merge pull request #2108 from private-octopus/faster_find_ready_tream'
PICOTLS_SHA       = 'f350eab60742138ac62b42ee444adf04c7898b0d'
PICOTLS_DESCRIBE  = 'f350eab'
PICOTLS_DATE      = '2025-07-16 15:55:42 +0900'
PICOTLS_SUBJECT   = 'Merge pull request #574 from h2o/kazuho/pr570'
