"""Build-time submodule revisions. Auto-generated by setup.py."""
PICOQUIC_SHA      = '2b1e14d5a46532eadf691edef5bd747da6de6557'
PICOQUIC_DESCRIBE = '2b1e14d5'
PICOQUIC_DATE     = '2026-05-15 21:56:50 -0700'
PICOQUIC_SUBJECT  = 'Merge pull request #2101 from victorstewart/bbr'
PICOTLS_SHA       = 'f350eab60742138ac62b42ee444adf04c7898b0d'
PICOTLS_DESCRIBE  = 'f350eab'
PICOTLS_DATE      = '2025-07-16 15:55:42 +0900'
PICOTLS_SUBJECT   = 'Merge pull request #574 from h2o/kazuho/pr570'
